image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      chmod +x gcloud-login.sh
      gcloud auth login --no-launch-browser
  - command: |
      echo "Ambiente Gitpod pronto"

vscode:
  extensions:
    - mhutchie.git-graph
    - phil294.git-log--graph
    - github.vscode-github-actions
    - GitHub.copilot
    - GitHub.copilot-chat
    - bierner.github-markdown-preview

github:
  prebuilds:
    # Ensure that prebuilds are used for the main branch and pull/merge requests
    branches:
      - main
    pullRequests: true
    # Trigger a new prebuild for any change in the repository
    watchPaths:
      - "**/*"


      
      