image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      chmod +x gcloud-login.sh
      gcloud auth login --no-launch-browser
  - command: |
      echo "Ambiente Gitpod pronto"

vscode:
  extensions:
    - mhutchie.git-graph
    - phil294.git-log--graph
    - github.vscode-github-actions
    - bierner.markdown-preview-github-styles
